### ISSUE TITLE
Error command bin/rails crawl:rss --trace

### ISSUE THREAD

**Issue by akameco** [SSconnect/SSConnectAPI#13]
Error `bin/rails crawl:rss --trace`

<details>
<summary>
log
</summary>

```sh
** Invoke crawl:rss (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute crawl:rss
佐竹細田速報
rails aborted!
Faraday::ConnectionFailed: Failed to open TCP connection to wuckert.ca:80 (getaddrinfo: nodename nor servname provided, or not known)
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:876:in `start'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:1165:in `get'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:33:in `call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/connection.rb:140:in `get'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/feedjira-2.1.1/lib/feedjira/feed.rb:68:in `fetch_and_parse'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/lib/tasks/crawl.rake:7:in `block (3 levels) in <top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/delegation.rb:38:in `each'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/delegation.rb:38:in `each'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/lib/tasks/crawl.rake:3:in `block (2 levels) in <top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/bin/rails:9:in `require'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/bin/rails:9:in `<top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
SocketError: Failed to open TCP connection to wuckert.ca:80 (getaddrinfo: nodename nor servname provided, or not known)
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:876:in `start'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:1165:in `get'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:33:in `call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/connection.rb:140:in `get'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/feedjira-2.1.1/lib/feedjira/feed.rb:68:in `fetch_and_parse'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/lib/tasks/crawl.rake:7:in `block (3 levels) in <top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/delegation.rb:38:in `each'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/delegation.rb:38:in `each'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/lib/tasks/crawl.rake:3:in `block (2 levels) in <top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/bin/rails:9:in `require'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/bin/rails:9:in `<top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
SocketError: getaddrinfo: nodename nor servname provided, or not known
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `initialize'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `open'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `block in connect'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:876:in `start'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/net/http.rb:1165:in `get'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:33:in `call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/faraday-0.11.0/lib/faraday/connection.rb:140:in `get'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/feedjira-2.1.1/lib/feedjira/feed.rb:68:in `fetch_and_parse'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/lib/tasks/crawl.rake:7:in `block (3 levels) in <top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/delegation.rb:38:in `each'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/delegation.rb:38:in `each'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/lib/tasks/crawl.rake:3:in `block (2 levels) in <top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/bin/rails:9:in `require'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/bin/rails:9:in `<top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/akameco/src/github.com/SSconnect/SSConnectAPI/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => crawl:rss
```
</details>

**Comment by elzup** [comment]
seed は有効な rss URL を生成してない

現状 crawl:rss は sample:insert_blog で生成した本番でも使ってるデータだと動く
